### ISSUE TITLE
Change to using GObject Introspection / GIR files for code generation

### ISSUE THREAD

**Issue by tylerburton** [coregtk/coregtk#3]
CoreGTK should have its code generated using GObject Introspection or be based off of GIR files. This will allow for easier GTK+ library change tracking and hopefully reduce future bugs.

**Comment by ttilley** [comment]
are you still working on this? I ask primarily because there will be an open source release of swift on linux in the mid-to-near-future, and I see a binding for GTK+ as being essential once this happens. GNUStep might have some useful functionality in their equivalent of Foundation, but their UI leaves much to be desired. ;)

**Comment by tylerburton** [comment]
Still working on it but it is slow goings with life being busy. You can see the latest update here: https://www.tylerburton.ca/2015/05/adding-gtk-3-support-and-building-coregtk-using-gobject-introspection/

**Comment by tylerburton** [comment]
Completed as of 13dea463619486277ed8adb868876ba2ddc8d84c

**Comment by ttilley** [comment]
glorious ^_^b
